### ISSUE TITLE
Squall::User#create is an instance method

### ISSUE THREAD

**Issue by moiristo** [Bweeb/squall#1]
Should be a class method, new you need to do 'Squall:User.new.create(...)'. For the other methods, I'd suggest creating an initializer in which you pass the id, after which you can call those methods without passing the id as a parameter.

**Comment by jmazzi** [comment]
We designed all the methods to be used as instances so you could easily execute multiple commands serially. 

``` ruby
@user = Squall::User.new
@user.create {}
@user.activate
@user.generate_api_key
```

**Comment by jmazzi** [comment]
I can see how a class method for some of the API methods could make more sense. We are talking about adding this internally.

I'm on the fence about your other suggestion. In our implementation we would be processing requests en masse. It doesn't really make sense to create 100 new class instances to suspend 100 users. What is your use case for?

**Comment by moiristo** [comment]
I see what you mean. I think it is nicer from an object oriented perspective, but I understand that in practice the current way is better. However, why wouldn't you make all methods class methods then? There's no point to instantiating the class in that case.

**Comment by jmazzi** [comment]
All the classes inherit from a base class right now. Changing them over to class methods would take a good bit of time/work. For now we'll keep it in mind, but don't have the time to rewrite most of the project. Unless of course you want to fork it and send some pull requests :)

**Comment by moiristo** [comment]
Ah, ok, so that's why this was implemented this way. It's fine with me then :) I might fork the project later when I need to use more of the API than just creating a user (which will probably be the case in the near future)..
