### ISSUE TITLE
Squall::User#create doesn't accept password_confirmation, role_ids

### ISSUE THREAD

**Issue by moiristo** [Bweeb/squall#2]
Plus, there are some other parameters that it should accept, e.g. billing_plan_id, suspend_after_hours. I'm not sure about user_group_id though as we already have group_id, maybe the API has been updated?

The OnApp documentation includes the following example:

curl -X POST -d "{user:{login:'login_testname', 
email:'test1@test.test',password_confirmation:'password_test1', first_name:'First', 
last_name:'Last',password:'password_test1',user_group_id:10, billing_plan_id:'1', 
suspend_after_hours:'1', role_ids:[1,2,3]}}" -u admin:password
http://onapp.test/users.json -H 'Accept: application/json' -H 'Content-type: 
application/json'

**Comment by jmazzi** [comment]
Squall was developed against an early release of OnApp 2.1. Some areas of the documentation were incomplete or wrong. Our team will take a look.

Which version of OnApp are you using?

**Comment by moiristo** [comment]
I think it is actually 2.1, but the documentation has been updated in may. It is publicly available on their website: http://cdn.onapp.com/files/onapp_2-1_api_guide_v1-11.pdf

**Comment by jmazzi** [comment]
We are in the process of updating to version 2.3. This should be fixed in the coming weeks.
