### ISSUE TITLE
Getting some difficulty when configure squall in rails 4

### ISSUE THREAD

**Issue by vishnurkrishnan** [Bweeb/squall#49]
Have put the squall-master in lib folder, and create one squall.yml in /squall-master/lib. It gives something like this when run the application 

/testOnapp/lib/squall-master/lib/squall.rb:47:in `<module:Squall>': undefined method`config' for Squall:Module (NoMethodError)
    from /home/TestApp/testOnapp/lib/squall-master/lib/squall.rb:7:in `<top (required)>'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in`require'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in`each'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `block in require'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in`each'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
    from /home/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.5.3/lib/bundler.rb:131:in`require'
    from /home/TestApp/testOnapp/config/application.rb:6:in `<top (required)>'
    from /home/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/commands.rb:74:in`require'
    from /home/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/commands.rb:74:in `block in <top (required)>'
    from /home/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/commands.rb:71:in`tap'
    from /home/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.2/lib/rails/commands.rb:71:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by itspriddle** [comment]
Are you using Bundler to load Squall? Try adding this to your Gemfile instead of cloning it in your app's `lib` directory:

``` ruby
gem "squall", github: "site5/squall", branch: "master"
```

**Comment by vishnurkrishnan** [comment]
oh thanks, so after that i can put that configuration in /config folder?

**Comment by itspriddle** [comment]
By default Squall searches for a config file at `~/.squall.yml`. If you want to keep it in your Rails app's config dir (e.g. `config/squall.yml`), create `config/initializers/squall.rb` with the following in it:

``` ruby
Squall.config_file Rails.root.join('config', 'squall.yml')
```

To test that it is working properly, load up your Rails console and enter `Squall.config`, and you should see something like this:

```
2.0.0-p353> Squall.config
=> {:username=>"myuser", :password=>"mypassword", :base_uri=>"http://example.com/", :debug=>true}
```

**Comment by vishnurkrishnan** [comment]
done!.Thank you
